name: Skin Library

on:
  push:
    paths:
      - 'Skins/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  skin-library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 5

      - name: Zip Skins
        run: cd Skins/; for i in *; do zip -r "$i.zip" $i; done;

      - name: Changes
        run: echo -e "Changes:\n" > changes.md && git --no-pager log -5 --oneline --no-decorate >> changes.md

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release edit skin-library -F changes.md
          gh release upload skin-library ./Skins/*.zip --clobber
